/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:385b4918-4a48-4653-b6d0-f1b4d5edbbb1",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_Umt8G6uvg",
    "aws_user_pools_web_client_id": "6a6e28r5hgmkvsdt2cl549a5l7",
    "oauth": {}
};


export default awsmobile;
